export const TEMPLATES = [
  {
    label: 'Flowchart',
    source: [
      'flowchart LR',
      '  A[Request] --> B{Cached?}',
      '  B -- yes --> C[Serve from cache]',
      '  B -- no --> D[Fetch origin]',
      '  D --> E[Store in cache]',
      '  E --> C',
    ].join('\n'),
  },
  {
    label: 'Sequence diagram',
    source: [
      'sequenceDiagram',
      '  participant U as User',
      '  participant A as API',
      '  participant D as Database',
      '  U->>A: POST /orders',
      '  A->>D: insert order',
      '  D-->>A: order id',
      '  A-->>U: 201 Created',
    ].join('\n'),
  },
  {
    label: 'Class diagram',
    source: [
      'classDiagram',
      '  class Order {',
      '    +String id',
      '    +Money total',
      '    +submit()',
      '  }',
      '  class LineItem {',
      '    +String sku',
      '    +int quantity',
      '  }',
      '  Order "1" --> "*" LineItem',
    ].join('\n'),
  },
  {
    label: 'State diagram',
    source: [
      'stateDiagram-v2',
      '  [*] --> Draft',
      '  Draft --> InReview: submit',
      '  InReview --> Draft: changes requested',
      '  InReview --> Approved: approve',
      '  Approved --> [*]',
    ].join('\n'),
  },
  {
    label: 'Entity relationship',
    source: [
      'erDiagram',
      '  CUSTOMER ||--o{ ORDER : places',
      '  ORDER ||--|{ LINE_ITEM : contains',
      '  PRODUCT ||--o{ LINE_ITEM : "appears in"',
    ].join('\n'),
  },
  {
    label: 'Gantt chart',
    source: [
      'gantt',
      '  title Release plan',
      '  dateFormat YYYY-MM-DD',
      '  section Build',
      '  Spec           :done,    spec, 2026-01-05, 5d',
      '  Implementation :active,  impl, after spec, 12d',
      '  section Ship',
      '  Review         :         rev,  after impl, 4d',
      '  Release        :milestone, after rev, 0d',
    ].join('\n'),
  },
  {
    label: 'Pie chart',
    source: [
      'pie showData',
      '  title Support tickets by area',
      '  "Billing" : 42',
      '  "Access" : 27',
      '  "Performance" : 18',
      '  "Other" : 13',
    ].join('\n'),
  },
  {
    label: 'Git graph',
    source: [
      'gitGraph',
      '  commit id: "init"',
      '  branch feature',
      '  checkout feature',
      '  commit id: "editor"',
      '  commit id: "preview"',
      '  checkout main',
      '  merge feature',
    ].join('\n'),
  },
  {
    label: 'Mindmap',
    source: [
      'mindmap',
      '  root((Documentation))',
      '    Reference',
      '      API',
      '      CLI',
      '    Guides',
      '      Getting started',
      '      Migration',
      '    Runbooks',
    ].join('\n'),
  },
  {
    label: 'User journey',
    source: [
      'journey',
      '  title Onboarding',
      '  section Sign up',
      '    Create account: 4: User',
      '    Verify email: 3: User',
      '  section First value',
      '    Import data: 2: User, Support',
      '    See first report: 5: User',
    ].join('\n'),
  },
];
